/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.pms;
import java.util.Scanner;

public class App {
  public static void main(String[] args) {
    System.out.println("[회원]");
    Scanner scanner = new Scanner(System.in);


    System.out.println("번호: ");
    int number = scanner.nextInt();
    scanner.nextLine();
    System.out.println("이름: ");
    String name = scanner.nextLine();
    System.out.println("이메일: ");
    String mail = scanner.nextLine();
    System.out.println("암호: ");
    int ps = scanner.nextInt();
    System.out.println("사진: ");
    int pi = scanner.nextInt();
    System.out.println("전화: ");
    int ph =scanner.nextInt();
    System.out.println("가입일: ");
    java.util.Date now = new java.util.Date();   

    scanner.close();

    System.out.println("----------------------------------");
    System.out.println("번호: "+ number);
    System.out.println("이름: "+ name);
    System.out.println("이메일: "+mail);
    System.out.println("암호: "+ps);
    System.out.println("사진: "+pi);
    System.out.println("전화: "+ph);
    System.out.println("가입일: "+now);
//ㅇㅇㅇㅇㅇㅇㅇㅇ
  }
}
