/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.pms;

public class App3 {
  public static void main(String[] args) {
    System.out.printf("[%s]\n", "작업" );
    System.out.printf("프로젝트: 미니 프로젝트 관리 시스템 개발 ");
    System.out.printf("번호: %s\n" ,"1 ");
    System.out.printf("내용: %s\n" ,"요구사항 수집 ");
    System.out.printf("완료일: %s\n" , "2020-01-20" );
    System.out.printf("상태: %s\n" ,"진행중" );
    System.out.printf("담당자: %s\n", "홍길동" );
  }
}
