/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.pms;
import java.util.Scanner;
public class App4 {
  public static void main(String[] args) {
    System.out.println("[회원]");
    Scanner scanner = new Scanner(System.in);

    final int SIZE = 8;

    int[] number = new int[SIZE];
    String[] name = new String[SIZE];
    String[] mail = new String[SIZE];
    String[] ps = new String[SIZE];
    String[] pi = new String[SIZE];
    String[] ph = new String[SIZE];
    java.util.Date[] now = new java.util.Date[SIZE];

    int count = 0;

    for (int i = 0; i < SIZE; i++) {

      System.out.print("번호: ");
      number [i] = scanner.nextInt();
      scanner.nextLine();
      System.out.print("이름: ");
      name [i] = scanner.nextLine();
      System.out.print("이메일: ");
      mail [i] = scanner.nextLine();
      System.out.print("암호: ");
      ps [i] = scanner.nextLine();
      System.out.print("사진: ");
      pi [i] = scanner.nextLine();
      System.out.print("전화: ");
      ph [i] = scanner.nextLine();
      now [i] = new java.util.Date();
      count ++;

      System.out.println();

      System.out.println("계속 입력하시겠습니까?(y/n)");
      String str = scanner.nextLine();
      if (str.equalsIgnoreCase("n") || str.length() == 0)  {
        break;
      }
      System.out.println();

    }

    scanner.close();
    System.out.println("----------------------------------");
    for (int i = 0; i < SIZE; i++) {

      System.out.printf("%d %s %s %s %s %s\n ",number[i] ,name[i] ,mail[i] ,ps[i] 
          ,pi[i] ,ph[i] ,now[i]);




    }
  }
}
