/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.pms;
import java.util.Scanner;
public class App6 {
  public static void main(String[] args) {
    Scanner scanner = new Scanner(System.in);

    final int SIZE = 100; 
    System.out.printf("[%s]\n", "작업" );

    String[] pro = new String[SIZE];
    int[] number = new int[SIZE];
    String[] content = new String[SIZE];
    String[] deadline = new String[SIZE];
    String[] name = new String[SIZE];
    int[] status = new int[SIZE];
    int size = 0;

    for (int i = 0; i < SIZE; i++) {
      System.out.printf("프로젝트?  ");
      pro[i] = scanner.nextLine();

      System.out.printf("번호:  ");
      number[i] = scanner.nextInt();

      scanner.nextLine();
      System.out.printf("내용:  ");
      content[i] = scanner.nextLine();

      System.out.printf("완료일: ");
      deadline[i] = scanner.nextLine();

      System.out.println("상태: " );
      System.out.println("o: 신규");
      System.out.println("1: 진행중");
      System.out.println("2: 완료");
      status[i] = Integer.valueOf(scanner.nextInt());

      scanner.nextLine();
      System.out.printf("담당자: " );
      name[i] = scanner.nextLine();


      size ++;

      System.out.println("계속 입력하시겠습니까?(y/n)");
      String str = scanner.nextLine();
      if (str.equalsIgnoreCase("n")) {
        break;
      }

    }
    scanner.close();


    System.out.printf("[%s]\n",pro);
    for (int i = 0; i < size; i++) {
      String st = null;
      switch (status[i]) {
        case 1:
          st = "진행중";
          break;
        case 2:
          st = "완료";
          break;
        default:
          st = "신규";
      }
      System.out.printf(" %d , %s , %s , %s , %s", number[i] , content[i] , deadline[i] , st, name[i]);

    }

  }
}
